/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConflictRouteImport } from './routes/conflict'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as LogRouteImport } from './routes/log'
import { Route as ScenarioRouteImport } from './routes/scenario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictRoute = ConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflict': typeof ConflictRoute
  '/decision': typeof DecisionRoute
  '/log': typeof LogRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflict': typeof ConflictRoute
  '/decision': typeof DecisionRoute
  '/log': typeof LogRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflict': typeof ConflictRoute
  '/decision': typeof DecisionRoute
  '/log': typeof LogRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conflict' | '/decision' | '/log' | '/scenario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conflict' | '/decision' | '/log' | '/scenario'
  id: '__root__' | '/' | '/conflict' | '/decision' | '/log' | '/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictRoute: typeof ConflictRoute
  DecisionRoute: typeof DecisionRoute
  LogRoute: typeof LogRoute
  ScenarioRoute: typeof ScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict': {
      id: '/conflict'
      path: '/conflict'
      fullPath: '/conflict'
      preLoaderRoute: typeof ConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictRoute: ConflictRoute,
  DecisionRoute: DecisionRoute,
  LogRoute: LogRoute,
  ScenarioRoute: ScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
